services:
  db:
    image: postgres:16-alpine
    container_name: flask-board-db
    environment:
      - POSTGRES_USER=flask
      - POSTGRES_PASSWORD=flask
      - POSTGRES_DB=flask_board
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flask -d flask_board"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    image: flask-board:compose
    container_name: flask-board
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql+psycopg2://flask:flask@db:5432/flask_board
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
