version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /Users/kpkuk/Desktop/ollama_models:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve & 
       sleep 5 && 
       ollama pull gemma3:1b && 
       tail -f /dev/null"
    restart: unless-stopped
